//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItem
    {
        public int BillItemId { get; set; }
        public string Furniture { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public string FurnitureShop { get; set; }
        public string FurnitureCategory { get; set; }
        public int BillId { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
