//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Furniture
    {
        public int FurnitureId { get; set; }

        [Required(ErrorMessage = "Code is required!")]
        [Remote("DoesCodeExist", "Furnitures", ErrorMessage = "Code already exists!")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }

        [Display(Name = "Country of Origin")]
        public string CountryOfOrigin { get; set; }

        [Display(Name = "Year Made")]
        public Nullable<int> YearMade { get; set; }

        [Required(ErrorMessage = "Price is required!")]
        public decimal Price { get; set; }

        [Display(Name = "Amount in Store")]
        [Range(0, int.MaxValue, ErrorMessage = "Amount cannot be a negative number!" )]
        public Nullable<int> AmountInStore { get; set; }

        public Nullable<int> FurnitureShopId { get; set; }        
        public Nullable<int> CategoryId { get; set; }

        public byte[] Photo { get; set; }
        public string PhotoType { get; set; }
    
        public virtual Category Category { get; set; }

        [Display(Name = "Furniture Shop")]
        public virtual FurnitureShop FurnitureShop { get; set; }
    }
}
